after_success: 
- mvn clean cobertura:cobertura coveralls:report -q
language: java
notifications: 
  recipients: 
  - miludmann+travis@gmail.com
  slack:
    rooms:
      secure: nCWjD+saKx7k5arMZFksP9xwHAPf1bDcluztPtYS7rwmAxhyn8v40BMwlSwUHHcjGGZB/Rp+ablnhe5AHnFtQY11C4tulScz/ruWG2L5X29m47uwr0sEzQa/rIq/Kms4ISF57zjPmppVTNKv4NbMQSL/Hcxfc69HctKJzKzcszY=
    on_success: always
    on_failure: always
  email: 
    on_success: change
    on_failure: always
install: 
- mvn validate -q
- mvn clean test
